### ISSUE TITLE
Patching

### ISSUE THREAD

**Issue by thanone2** [aspieweeb759/Super_Mario_64_DS_N64_Restoration#1]
I tried using xdeltaUI to patch the rom but it doesn't work it says "xdelta3: unknown secondary compresser ID: XD3_INVALID_INPUT idk what to do I put in all the parameters I needed to and it doesn't like it.

**Comment by aspieweeb759** [comment]
Tbh, I have no idea what that error means, all I can tell you is to make
sure your using the US V1.0 of sm64 ds to patch the mod

**Comment by thanone2** [comment]
my rom says "Rev 1"

**Comment by thanone2** [comment]
nvm found out my rom was 1.1
